### ISSUE TITLE
[BUG]: piece got auto updated 

### ISSUE THREAD

**Issue by saksham-procol** [activepieces/activepieces#4090]
**Bug Description**
My previous flows were using version 1.1 for this piece, but some how when i published a new flow with this piece it got bumped to 1.3 and started failing for the shown reason in the attached SS

when i searched for the error in the code base i didn't find any results
my app version at the time was 18.x.x

**Expected Behaviour**
The piece should maintain its version (1.1) and function without failures when incorporated into the new flow.

**Screenshots**
![Screenshot 2024-03-05 at 3 29 03 PM](https://github.com/activepieces/activepieces/assets/125830044/0fc3adb0-cfc1-41ad-88d9-09d382917eb3)
![Screenshot 2024-03-05 at 3 29 19 PM](https://github.com/activepieces/activepieces/assets/125830044/6666e319-c59f-4c09-9438-ddfaab797975)

**Additional Information**
Running the application on a self hosted server
error: `ctx.generateResumeUrl is not a function`

**Comment by abuaboud** [comment]
Hi @saksham-procol,

I believe the issue occurred after you upgraded the instance, causing the approval workflow to break, correct? Here's the link for reference: https://community.activepieces.com/t/action-required-breaking-changes-approval-piece-on-0-20-0/3063

Because version 0.1.3 shouldn't be available in 0.1.18, did I understand correctly?

**Comment by saksham-procol** [comment]
> Hi @saksham-procol,
> 
> I believe the issue occurred after you upgraded the instance, causing the approval workflow to break, correct? Here's the link for reference: https://community.activepieces.com/t/action-required-breaking-changes-approval-piece-on-0-20-0/3063
> 
> Because version 0.1.3 shouldn't be available in 0.1.18, did I understand correctly?

Hi @abuaboud 
the issue occurred when i published a new workflow (duplicated from an existing workflow). Now since i didn't update/change anything in the code base codebase version 0.1.3 shouldn't be available, it should remain 0.1.18

**Comment by abuaboud** [comment]
Hi @saksham-procol 

You are right, This should be fixed, 0.1.3 is no longer available on 0.18.0.

Thank you!

**Comment by saksham-procol** [comment]
I have a follow up question..
If i didn't sync the forked repo with the upstream, how did the dependency of the piece changed . Earlier approval piece 0.1.3 was working fine with app version 0.18.0 , and if i didn't update the code base at all, how did approval piece 0.1.3 suddenly stopped supporting app version 0.18.0

**Comment by abuaboud** [comment]
Hi @saksham-procol pieces are loaded directly from npmjs, they are not inside the docker container in each npm package there is minimum and maximum support version 

https://www.npmjs.com/search?q=%40activepieces
